# Generated by Django 2.2.2 on 2019-06-27 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='year')),
                ('unit_id', models.CharField(blank=True, max_length=20, verbose_name='unit id')),
                ('camp_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='camp id')),
                ('unit_type', models.CharField(blank=True, max_length=20, verbose_name='type')),
                ('unit_title', models.CharField(blank=True, max_length=20, verbose_name='title')),
                ('unit_name_l', models.CharField(blank=True, max_length=120, verbose_name='name l')),
                ('unit_name_s', models.CharField(blank=True, max_length=20, verbose_name='name s')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('resp_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='resp id')),
                ('account', models.CharField(blank=True, max_length=20, null=True, verbose_name='account')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='year')),
                ('inst_id', models.CharField(blank=True, max_length=20, verbose_name='inst id')),
                ('inst_e_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='inst e id')),
                ('inst_type', models.CharField(blank=True, max_length=20, verbose_name='type')),
                ('inst_title', models.CharField(blank=True, max_length=20, verbose_name='title')),
                ('inst_name_l', models.CharField(blank=True, max_length=120, verbose_name='name l')),
                ('inst_name_s', models.CharField(blank=True, max_length=20, verbose_name='name s')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('fiscal_id', models.CharField(blank=True, max_length=20, verbose_name='fiscal id')),
                ('inst_e2_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='inst e2 id')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('photo', models.ImageField(blank=True, default='inst/default.png', null=True, upload_to='inst', verbose_name='photo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'inst',
                'verbose_name_plural': 'insts',
                'unique_together': {('year', 'fiscal_id', 'inst_name_s')},
            },
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='year')),
                ('camp_id', models.CharField(blank=True, max_length=20, verbose_name='camp id')),
                ('inst_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='inst id')),
                ('camp_type', models.CharField(blank=True, max_length=20, verbose_name='type')),
                ('camp_title', models.CharField(blank=True, max_length=20, verbose_name='title')),
                ('camp_name_l', models.CharField(blank=True, max_length=120, verbose_name='name l')),
                ('camp_name_s', models.CharField(blank=True, max_length=20, verbose_name='name s')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('resp_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='resp id')),
                ('account', models.CharField(blank=True, max_length=20, null=True, verbose_name='account')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('photo', models.ImageField(blank=True, default='camp/default.png', null=True, upload_to='camp', verbose_name='photo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'camp',
                'verbose_name_plural': 'camps',
                'unique_together': {('year', 'camp_name_s')},
            },
        ),
    ]
